
/**
 * Interface representing revenue data per sales representative
 * rep_id: Unique identifier for the sales representative
 * rep_name: Name of the sales representative
 * revenue: Total revenue generated by the sales representative
 * deals_closed: Number of deals closed by the sales representative
 * quota_attainment: Percentage of quota attained by the sales representative (e.g., 0.75 for 75%)
 */
export interface IRevenuePerSalesRep {
  rep_id: string;
  rep_name: string;
  revenue: number;
  deals_closed: number;
  quota_attainment: number;
}

export enum IDateRange {
  THIS_QUARTER = 'this_quarter',
  THIS_MONTH = 'this_month',
  THIS_YEAR = 'this_year'
}