import { AfterViewInit, ChangeDetectorRef, Component, ElementRef, EventEmitter, inject, Inject, Input, OnChanges, OnDestroy, OnInit, Output, SimpleChanges, ViewChild } from '@angular/core';
import { IDateRange, IRevenuePerSalesRep } from './revenue-per-sales-reps.interface';
import { RevenuePerSalesRepsService } from './revenue-per-sales-reps.service';
import { CommonModule } from '@angular/common';
import { debounceTime, distinctUntilChanged, finalize, map, Subject, switchMap, takeUntil, tap } from 'rxjs';
import { Chart } from 'chart.js/auto';
import { RenderState } from '../interfaces/component-render-state.interface';
/**
 * Main functional requirements
 * - spinner when load
 * - show chart
 * - show ui when error retry butotn
 * - Data load again when input change
 */

export interface IChartView {
  title: string;
  description: string;
}
@Component({
  standalone: true,
  selector: 'app-revenue-per-sales-rep',
  imports: [
    CommonModule,
  ],
  providers: [RevenuePerSalesRepsService],
  templateUrl: './revenue-per-sales-rep.component.html',
  styleUrls: ['./revenue-per-sales-rep.component.css']
})
export class RevenuePerSalesRepComponent implements OnInit, OnDestroy, AfterViewInit, OnChanges {
  @Input() dateRange: IDateRange | null = null;
  @Input() view: IChartView = {
    title: 'Revenue per Sales Rep',
    description: 'Breakdown of revenue generated by each sales representative.'
  };
  @ViewChild('chartCanvas') chartCanvas!: ElementRef<HTMLCanvasElement>;

  cdr = inject(ChangeDetectorRef);
  revenuePerSalesRepsService = inject(RevenuePerSalesRepsService);
  // Behavior
  chart?: Chart;
  renderState: RenderState = RenderState.LOADING;
  errorMessage = '';

  loadTrigger$ = new Subject<IDateRange | null>()
  destroy$$ = new Subject<void>();
  errorMap: Record<string, string> = {
    '500': 'Failed to load data. Please try again.',
    '404': 'Data not found.'
  }

  constructor() { }
  ngOnChanges(changes: SimpleChanges): void {
    if (changes['dateRange'] && !changes['dateRange'].firstChange) {
      this.loadTrigger$.next(this.dateRange);
    }
  }

  ngOnInit() {
    this.prepareTrigger();
  }

  ngAfterViewInit() {
    this.loadTrigger$.next(this.dateRange);
  }

  ngOnDestroy(): void {
    this.destroyChart();
    this.destroy$$.next();
    this.destroy$$.complete();
  }

  onReload() {
    this.loadTrigger$.next(this.dateRange);
  }
  changeRenderState(renderState: RenderState, message?: string) {
    this.renderState = renderState;
    this.errorMessage = message || '';
    this.cdr.markForCheck();
  }

  private _transformToChartData(data: IRevenuePerSalesRep[]) {
    const labels: Array<string> = []
    const dataValues: Array<number> = []
    const datasets: Array<{ label: string; data: number[] }> = [{
      label: 'Revenue',
      data: []
    }];
    if (data.length === 0) {
      return { labels, datasets };
    }
    for (const item of data) {
      labels.push(item.rep_name);
      dataValues.push(item.revenue);
    }
    datasets[0].data = dataValues;
    return { labels, datasets };
  }


  renderChart(chartData: any) {
    const ctx = this.chartCanvas.nativeElement.getContext('2d');
    if (!ctx) return;
    if (this.chart) {
      this.chart.data.labels = chartData.labels;
      this.chart.data.datasets = chartData.datasets;
      this.chart.update();
      return;
    }
    this.chart = new Chart(ctx, {
      type: 'pie',
      data: {
        labels: chartData.labels,
        datasets: chartData.datasets
      },
      options: {
        responsive: true,
      },
    });
  }

  destroyChart() {
    if (this.chart) {
      this.chart.destroy();
    }
    this.errorMessage = '';
  }

  prepareTrigger() {
    this.loadTrigger$.pipe(
      tap(() => {
        this.errorMessage = '';
        this.changeRenderState(RenderState.LOADING);
      }),
      debounceTime(300),
      switchMap((dateRange) => this.revenuePerSalesRepsService.getSalesRepRevenue(dateRange)),
      map(res => res.sales_rep_performance),
      map(data => this._transformToChartData(data)),
      takeUntil(this.destroy$$),
      finalize(() => {
        // Có thể dùng để dọn dẹp hoặc reset state nếu cần sau khi observable hoàn thành
      })
    ).subscribe({
      next: (chartData) => {
        if (chartData.datasets[0].data.length == 0) {
          this.changeRenderState(RenderState.EMPTY);
          return;
        }
        this.changeRenderState(RenderState.LOADED);
        this.renderChart(chartData);
      },
      error: (err) => {
        console.error('Error fetching revenue per sales rep data:', err);
        const errorMessage = this.errorMap[err.status] || 'An unexpected error occurred.';
        this.changeRenderState(RenderState.ERROR, errorMessage);
      }
    })
  }
}
